name: Interoperability tests
on: push
permissions:
  contents: read
jobs:
  trigger:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Trigger interoperability tests in str4d/rage
        run: |
          printenv GITHUB_SHA |
          jq --raw-input '{event_type: "age-interop-request", client_payload: {sha: .}}' |
          gh api /repos/str4d/rage/dispatches --input -
        env:
          GITHUB_TOKEN: ${{ secrets.RAGE_INTEROP_ACCESS_TOKEN }}
