on: push
jobs:
  freebsd:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - uses: vmactions/freebsd-vm@v0
        with:
          prepare: pkg install -y go
          run: go test -buildvcs=false -race ./...
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
