name: Go tests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  gotip:
    name: Test (Go tip)
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install bootstrap Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Go tip (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone --filter=tree:0 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src && ./make.bat
          echo "$HOME/gotip/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - if: always()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: go version
      - name: Run tests
        run: go test -race ./...
